In [55]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")
books = books.drop(columns=["simple_classification"]) #cleanup

In [57]:
from dotenv import load_dotenv
load_dotenv()

True

In [58]:
##### Load in emotion classification model
from transformers import pipeline

# can look at the documentation for this model to see how well the model did in the training
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = "mps")
classifier("I love this!")

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528684265911579},
  {'label': 'neutral', 'score': 0.005764600355178118},
  {'label': 'anger', 'score': 0.004419781267642975},
  {'label': 'sadness', 'score': 0.002092392183840275},
  {'label': 'disgust', 'score': 0.001611993182450533},
  {'label': 'fear', 'score': 0.0004138521908316761}]]

In [59]:
###### decide which level of description we want to apply the sentiment analysis over -> overall description or each sentence in the description
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [60]:
# sentiment analyzer over description:
classifier(books["description"][0]) # desc in general doesn't feel that fearful besides one or two parts

[[{'label': 'fear', 'score': 0.654841423034668},
  {'label': 'neutral', 'score': 0.16985200345516205},
  {'label': 'sadness', 'score': 0.11640875786542892},
  {'label': 'surprise', 'score': 0.02070065401494503},
  {'label': 'disgust', 'score': 0.019100766628980637},
  {'label': 'joy', 'score': 0.015161258168518543},
  {'label': 'anger', 'score': 0.003935154993087053}]]

In [61]:
# sentiment analyzer over each sentence:
classifier(books["description"][0].split(".")) # classifer allows you to pass in multiple arguments, result gives you more variants in emotions

[[{'label': 'surprise', 'score': 0.7296027541160583},
  {'label': 'neutral', 'score': 0.1403856724500656},
  {'label': 'fear', 'score': 0.06816212832927704},
  {'label': 'joy', 'score': 0.047942448407411575},
  {'label': 'anger', 'score': 0.009156345389783382},
  {'label': 'disgust', 'score': 0.0026284728664904833},
  {'label': 'sadness', 'score': 0.002122161677107215}],
 [{'label': 'neutral', 'score': 0.44937166571617126},
  {'label': 'disgust', 'score': 0.2735905349254608},
  {'label': 'joy', 'score': 0.10908280313014984},
  {'label': 'sadness', 'score': 0.09362749755382538},
  {'label': 'anger', 'score': 0.040478236973285675},
  {'label': 'surprise', 'score': 0.02697022631764412},
  {'label': 'fear', 'score': 0.006879068911075592}],
 [{'label': 'neutral', 'score': 0.6462157964706421},
  {'label': 'sadness', 'score': 0.24273350834846497},
  {'label': 'disgust', 'score': 0.0434226468205452},
  {'label': 'surprise', 'score': 0.028300516307353973},
  {'label': 'joy', 'score': 0.01421145349740982},
  {'label': 'fear', 'score': 0.014084119349718094},
  {'label': 'anger', 'score': 0.011031894013285637}],
 [{'label': 'fear', 'score': 0.9281684160232544},
  {'label': 'anger', 'score': 0.03219081833958626},
  {'label': 'neutral', 'score': 0.01280867401510477},
  {'label': 'sadness', 'score': 0.008756855502724648},
  {'label': 'surprise', 'score': 0.008597873151302338},
  {'label': 'disgust', 'score': 0.008431804366409779},
  {'label': 'joy', 'score': 0.0010455820010975003}],
 [{'label': 'sadness', 'score': 0.9671574234962463},
  {'label': 'neutral', 'score': 0.015104176476597786},
  {'label': 'disgust', 'score': 0.006480601150542498},
  {'label': 'fear', 'score': 0.005393999628722668},
  {'label': 'surprise', 'score': 0.00228694174438715},
  {'label': 'anger', 'score': 0.0018428900511935353},
  {'label': 'joy', 'score': 0.0017338786274194717}],
 [{'label': 'joy', 'score': 0.9327980279922485},
  {'label': 'disgust', 'score': 0.03771708533167839},
  {'label': 'neutral', 'score': 0.015891848132014275},
  {'label': 'sadness', 'score': 0.006444487255066633},
  {'label': 'anger', 'score': 0.005024975165724754},
  {'label': 'surprise', 'score': 0.001581205753609538},
  {'label': 'fear', 'score': 0.0005423066904768348}],
 [{'label': 'joy', 'score': 0.6528699398040771},
  {'label': 'neutral', 'score': 0.25427526235580444},
  {'label': 'surprise', 'score': 0.06808328628540039},
  {'label': 'sadness', 'score': 0.00990901980549097},
  {'label': 'disgust', 'score': 0.006512223277240992},
  {'label': 'anger', 'score': 0.004821322858333588},
  {'label': 'fear', 'score': 0.003529022680595517}],
 [{'label': 'neutral', 'score': 0.5494773983955383},
  {'label': 'sadness', 'score': 0.11169008165597916},
  {'label': 'disgust', 'score': 0.10400652140378952},
  {'label': 'surprise', 'score': 0.07876541465520859},
  {'label': 'anger', 'score': 0.06413350999355316},
  {'label': 'fear', 'score': 0.05136270076036453},
  {'label': 'joy', 'score': 0.04056432843208313}]]

In [62]:
# double check: look at individual sentences and see if its giving us the right predictions
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [47]:
sentences[0]

"Since the three volume edition ofHegel's Philosophy of Subjective Spirit (1978, 19792) has been so well received, I have been encouraged to select that part of it most suitable for teaching purposes, and to publish it here as a separate work"

In [48]:
predictions[0]

[{'label': 'joy', 'score': 0.9585492610931396},
 {'label': 'neutral', 'score': 0.02825169824063778},
 {'label': 'surprise', 'score': 0.0031422830652445555},
 {'label': 'disgust', 'score': 0.0031370013020932674},
 {'label': 'sadness', 'score': 0.0029162841383367777},
 {'label': 'anger', 'score': 0.002837192267179489},
 {'label': 'fear', 'score': 0.0011662733741104603}]

In [49]:
sentences[3]

" Since it consists for the most part of a searching and radical analysis of Kant's epistemology, Fichte's ethics and Schelling's system-building, it provides tirst-rate insight into Hegel's assessment of his immedi~te predecessors"

In [50]:
predictions[3]

[{'label': 'neutral', 'score': 0.9151931405067444},
 {'label': 'disgust', 'score': 0.02325638383626938},
 {'label': 'surprise', 'score': 0.0229833722114563},
 {'label': 'fear', 'score': 0.012683776207268238},
 {'label': 'anger', 'score': 0.011929994449019432},
 {'label': 'joy', 'score': 0.010555327869951725},
 {'label': 'sadness', 'score': 0.0033980514854192734}]

In [ ]:
# conclusion: these predictions make sense and the classifier is doing a good job

In [63]:
##### Introduce a new column that holds the highest value for each 7 emotion across all the sentences for every book

predictions # need to combine these to where it keeps the highest score of the emotions

[[{'label': 'surprise', 'score': 0.7296027541160583},
  {'label': 'neutral', 'score': 0.1403856724500656},
  {'label': 'fear', 'score': 0.06816212832927704},
  {'label': 'joy', 'score': 0.047942448407411575},
  {'label': 'anger', 'score': 0.009156345389783382},
  {'label': 'disgust', 'score': 0.0026284728664904833},
  {'label': 'sadness', 'score': 0.002122161677107215}],
 [{'label': 'neutral', 'score': 0.44937166571617126},
  {'label': 'disgust', 'score': 0.2735905349254608},
  {'label': 'joy', 'score': 0.10908280313014984},
  {'label': 'sadness', 'score': 0.09362749755382538},
  {'label': 'anger', 'score': 0.040478236973285675},
  {'label': 'surprise', 'score': 0.02697022631764412},
  {'label': 'fear', 'score': 0.006879068911075592}],
 [{'label': 'neutral', 'score': 0.6462157964706421},
  {'label': 'sadness', 'score': 0.24273350834846497},
  {'label': 'disgust', 'score': 0.0434226468205452},
  {'label': 'surprise', 'score': 0.028300516307353973},
  {'label': 'joy', 'score': 0.01421145349740982},
  {'label': 'fear', 'score': 0.014084119349718094},
  {'label': 'anger', 'score': 0.011031894013285637}],
 [{'label': 'fear', 'score': 0.9281684160232544},
  {'label': 'anger', 'score': 0.03219081833958626},
  {'label': 'neutral', 'score': 0.01280867401510477},
  {'label': 'sadness', 'score': 0.008756855502724648},
  {'label': 'surprise', 'score': 0.008597873151302338},
  {'label': 'disgust', 'score': 0.008431804366409779},
  {'label': 'joy', 'score': 0.0010455820010975003}],
 [{'label': 'sadness', 'score': 0.9671574234962463},
  {'label': 'neutral', 'score': 0.015104176476597786},
  {'label': 'disgust', 'score': 0.006480601150542498},
  {'label': 'fear', 'score': 0.005393999628722668},
  {'label': 'surprise', 'score': 0.00228694174438715},
  {'label': 'anger', 'score': 0.0018428900511935353},
  {'label': 'joy', 'score': 0.0017338786274194717}],
 [{'label': 'joy', 'score': 0.9327980279922485},
  {'label': 'disgust', 'score': 0.03771708533167839},
  {'label': 'neutral', 'score': 0.015891848132014275},
  {'label': 'sadness', 'score': 0.006444487255066633},
  {'label': 'anger', 'score': 0.005024975165724754},
  {'label': 'surprise', 'score': 0.001581205753609538},
  {'label': 'fear', 'score': 0.0005423066904768348}],
 [{'label': 'joy', 'score': 0.6528699398040771},
  {'label': 'neutral', 'score': 0.25427526235580444},
  {'label': 'surprise', 'score': 0.06808328628540039},
  {'label': 'sadness', 'score': 0.00990901980549097},
  {'label': 'disgust', 'score': 0.006512223277240992},
  {'label': 'anger', 'score': 0.004821322858333588},
  {'label': 'fear', 'score': 0.003529022680595517}],
 [{'label': 'neutral', 'score': 0.5494773983955383},
  {'label': 'sadness', 'score': 0.11169008165597916},
  {'label': 'disgust', 'score': 0.10400652140378952},
  {'label': 'surprise', 'score': 0.07876541465520859},
  {'label': 'anger', 'score': 0.06413350999355316},
  {'label': 'fear', 'score': 0.05136270076036453},
  {'label': 'joy', 'score': 0.04056432843208313}]]

In [64]:
# sort the scores of each sentence:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.009156345389783382},
 {'label': 'disgust', 'score': 0.0026284728664904833},
 {'label': 'fear', 'score': 0.06816212832927704},
 {'label': 'joy', 'score': 0.047942448407411575},
 {'label': 'neutral', 'score': 0.1403856724500656},
 {'label': 'sadness', 'score': 0.002122161677107215},
 {'label': 'surprise', 'score': 0.7296027541160583}]

In [65]:
# extract max emotion probability
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
# contains all the scores for every description for each of the labels:
emotion_scores= {label: [] for label in emotion_labels}

def get_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions: #every sentence in the description
        sorted_predictions = sorted(prediction, key=lambda x: x["label"]) # sort the result of the prediction for the sentence
        for index, label in enumerate(emotion_labels): # for each of the emotions, attach the score of the emotion
            per_emotion_scores[label].append(sorted_predictions[index]["score"])

    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [66]:
# testing for first ten books
for i in range(10):
    isbn.append(books["isbn13"][i]) # attach the isbn into our new list
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_score = get_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_score[label])

In [67]:
emotion_scores # yay this works!

{'anger': [np.float64(0.06413350999355316),
  np.float64(0.6126183867454529),
  np.float64(0.06413350999355316),
  np.float64(0.3514830768108368),
  np.float64(0.08141231536865234),
  np.float64(0.23222483694553375),
  np.float64(0.5381841063499451),
  np.float64(0.06413350999355316),
  np.float64(0.3006706237792969),
  np.float64(0.06413350999355316)],
 'disgust': [np.float64(0.2735905349254608),
  np.float64(0.348285436630249),
  np.float64(0.10400652140378952),
  np.float64(0.1507226973772049),
  np.float64(0.18449489772319794),
  np.float64(0.7271748185157776),
  np.float64(0.15585489571094513),
  np.float64(0.10400652140378952),
  np.float64(0.27948111295700073),
  np.float64(0.17792636156082153)],
 'fear': [np.float64(0.9281684160232544),
  np.float64(0.942527711391449),
  np.float64(0.9723208546638489),
  np.float64(0.3607070744037628),
  np.float64(0.09504328668117523),
  np.float64(0.05136270076036453),
  np.float64(0.747427761554718),
  np.float64(0.4044956862926483),
  np.float64(0.9155241250991821),
  np.float64(0.05136270076036453)],
 'joy': [np.float64(0.9327980279922485),
  np.float64(0.7044215202331543),
  np.float64(0.7672367691993713),
  np.float64(0.25188055634498596),
  np.float64(0.04056432843208313),
  np.float64(0.04337586835026741),
  np.float64(0.8725650906562805),
  np.float64(0.04056432843208313),
  np.float64(0.04056432843208313),
  np.float64(0.04056432843208313)],
 'sadness': [np.float64(0.6462157964706421),
  np.float64(0.8879395127296448),
  np.float64(0.5494773983955383),
  np.float64(0.7326871156692505),
  np.float64(0.8843894600868225),
  np.float64(0.6213928461074829),
  np.float64(0.7121942639350891),
  np.float64(0.5494773983955383),
  np.float64(0.8402898907661438),
  np.float64(0.8603722453117371)],
 'surprise': [np.float64(0.9671574234962463),
  np.float64(0.11169008165597916),
  np.float64(0.11169008165597916),
  np.float64(0.11169008165597916),
  np.float64(0.47588104009628296),
  np.float64(0.11169008165597916),
  np.float64(0.40799808502197266),
  np.float64(0.8202821612358093),
  np.float64(0.3544599711894989),
  np.float64(0.11169008165597916)],
 'neutral': [np.float64(0.7296027541160583),
  np.float64(0.25254493951797485),
  np.float64(0.07876541465520859),
  np.float64(0.07876541465520859),
  np.float64(0.07876541465520859),
  np.float64(0.27190250158309937),
  np.float64(0.07876541465520859),
  np.float64(0.23448757827281952),
  np.float64(0.13561438024044037),
  np.float64(0.07876541465520859)]}

In [68]:
# now apply to ALL the books
from tqdm import tqdm

# reset from last run
emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores= {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i]) # attach the isbn into our new list
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_score = get_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_score[label])

  0%|          | 0/5197 [00:00<?, ?it/s]
  0%|          | 1/5197 [00:00<09:59,  8.67it/s]
  0%|          | 2/5197 [00:00<09:31,  9.09it/s]
  0%|          | 5/5197 [00:00<05:57, 14.52it/s]
  0%|          | 7/5197 [00:00<07:08, 12.11it/s]
  0%|          | 9/5197 [00:00<06:40, 12.95it/s]
  0%|          | 12/5197 [00:00<06:02, 14.30it/s]
  0%|          | 14/5197 [00:01<07:08, 12.09it/s]
  0%|          | 16/5197 [00:01<06:37, 13.03it/s]
  0%|          | 20/5197 [00:01<04:56, 17.46it/s]
  0%|          | 24/5197 [00:01<04:08, 20.85it/s]
  1%|          | 27/5197 [00:01<04:31, 19.04it/s]
  1%|          | 30/5197 [00:01<04:51, 17.74it/s]
  1%|          | 32/5197 [00:02<05:02, 17.08it/s]
  1%|          | 34/5197 [00:02<05:16, 16.31it/s]
  1%|          | 36/5197 [00:02<05:20, 16.11it/s]
  1%|          | 38/5197 [00:02<05:56, 14.48it/s]
  1%|          | 41/5197 [00:02<05:00, 17.14it/s]
  1%|          | 43/5197 [00:02<06:11, 13.87it/s]
  1%|          | 45/5197 [00:02<05:54, 14.51it/s]
  1%|          | 47/5197 [00:03<06:02, 14.20it/s]
  1%|          | 49/5197 [00:03<07:06, 12.06it/s]
  1%|          | 52/5197 [00:03<05:49, 14.73it/s]
  1%|          | 55/5197 [00:03<05:11, 16.49it/s]
  1%|          | 59/5197 [00:03<05:15, 16.30it/s]
  1%|          | 63/5197 [00:04<04:32, 18.82it/s]
  1%|▏         | 65/5197 [00:04<05:14, 16.34it/s]
  1%|▏         | 67/5197 [00:04<05:09, 16.58it/s]
  1%|▏         | 69/5197 [00:04<05:38, 15.15it/s]
  1%|▏         | 71/5197 [00:04<07:35, 11.25it/s]
  1%|▏         | 73/5197 [00:04<07:33, 11.31it/s]
  1%|▏         | 76/5197 [00:05<07:11, 11.86it/s]
  2%|▏         | 78/5197 [00:05<06:51, 12.44it/s]
  2%|▏         | 80/5197 [00:05<06:52, 12.42it/s]
  2%|▏         | 83/5197 [00:05<06:23, 13.33it/s]
  2%|▏         | 85/5197 [00:05<06:33, 13.01it/s]
  2%|▏         | 88/5197 [00:05<05:30, 15.45it/s]
  2%|▏         | 91/5197 [00:06<05:00, 17.01it/s]
  2%|▏         | 93/5197 [00:06<06:47, 12.52it/s]
  2%|▏         | 95/5197 [00:06<07:46, 10.94it/s]
  2%|▏         | 98/5197 [00:06<06:30, 13.05it/s]
  2%|▏         | 100/5197 [00:06<05:56, 14.29it/s]
  2%|▏         | 102/5197 [00:07<05:40, 14.96it/s]
  2%|▏         | 104/5197 [00:07<06:33, 12.93it/s]
  2%|▏         | 106/5197 [00:07<07:00, 12.12it/s]
  2%|▏         | 108/5197 [00:07<06:37, 12.79it/s]
  2%|▏         | 110/5197 [00:07<06:13, 13.63it/s]
  2%|▏         | 112/5197 [00:07<05:42, 14.84it/s]
  2%|▏         | 114/5197 [00:07<05:56, 14.28it/s]
  2%|▏         | 116/5197 [00:08<05:39, 14.98it/s]
  2%|▏         | 119/5197 [00:08<05:32, 15.27it/s]
  2%|▏         | 121/5197 [00:08<05:33, 15.20it/s]
  2%|▏         | 123/5197 [00:08<06:51, 12.33it/s]
  2%|▏         | 125/5197 [00:08<08:27,  9.99it/s]
  2%|▏         | 127/5197 [00:09<08:20, 10.14it/s]
  2%|▏         | 129/5197 [00:09<08:43,  9.68it/s]
  3%|▎         | 131/5197 [00:09<08:09, 10.35it/s]
  3%|▎         | 133/5197 [00:09<07:44, 10.91it/s]
  3%|▎         | 135/5197 [00:09<09:00,  9.37it/s]
  3%|▎         | 137/5197 [00:10<08:31,  9.90it/s]
  3%|▎         | 139/5197 [00:10<10:03,  8.38it/s]
  3%|▎         | 143/5197 [00:10<06:26, 13.09it/s]
  3%|▎         | 146/5197 [00:10<05:52, 14.35it/s]
  3%|▎         | 148/5197 [00:10<06:02, 13.92it/s]
  3%|▎         | 150/5197 [00:11<06:33, 12.82it/s]
  3%|▎         | 152/5197 [00:11<06:47, 12.39it/s]
  3%|▎         | 154/5197 [00:11<06:10, 13.61it/s]
  3%|▎         | 156/5197 [00:11<05:46, 14.54it/s]
  3%|▎         | 159/5197 [00:11<04:46, 17.61it/s]
  3%|▎         | 161/5197 [00:11<04:57, 16.94it/s]
  3%|▎         | 163/5197 [00:11<06:44, 12.44it/s]
  3%|▎         | 165/5197 [00:12<07:13, 11.60it/s]
  3%|▎         | 167/5197 [00:12<07:28, 11.22it/s]
  3%|▎         | 169/5197 [00:12<06:35, 12.71it/s]
  3%|▎         | 171/5197 [00:12<06:58, 12.00it/s]
  3%|▎         | 173/5197 [00:13<10:41,  7.83it/s]
  3%|▎         | 175/5197 [00:13<10:01,  8.35it/s]
  3%|▎         | 177/5197 [00:13<09:30,  8.80it/s]
  3%|▎         | 179/5197 [00:13<08:00, 10.44it/s]
  3%|▎         | 181/5197 [00:13<09:48,  8.52it/s]
  4%|▎         | 183/5197 [00:14<09:19,  8.96it/s]
  4%|▎         | 185/5197 [00:14<09:32,  8.75it/s]
  4%|▎         | 186/5197 [00:14<09:34,  8.72it/s]
  4%|▎         | 189/5197 [00:14<07:01, 11.87it/s]
  4%|▎         | 191/5197 [00:14<06:18, 13.24it/s]
  4%|▎         | 193/5197 [00:14<06:51, 12.17it/s]
  4%|▍         | 195/5197 [00:15<07:25, 11.23it/s]
  4%|▍         | 197/5197 [00:15<08:18, 10.03it/s]
  4%|▍         | 199/5197 [00:15<07:55, 10.52it/s]
  4%|▍         | 201/5197 [00:15<07:34, 10.98it/s]
  4%|▍         | 204/5197 [00:15<06:19, 13.17it/s]
  4%|▍         | 206/5197 [00:16<05:57, 13.97it/s]
  4%|▍         | 208/5197 [00:16<05:34, 14.93it/s]
  4%|▍         | 210/5197 [00:16<05:37, 14.78it/s]
  4%|▍         | 212/5197 [00:16<05:21, 15.49it/s]
  4%|▍         | 215/5197 [00:16<05:06, 16.25it/s]
  4%|▍         | 218/5197 [00:16<04:54, 16.89it/s]
  4%|▍         | 220/5197 [00:16<04:45, 17.44it/s]
  4%|▍         | 222/5197 [00:16<04:50, 17.15it/s]
  4%|▍         | 224/5197 [00:17<05:39, 14.66it/s]
  4%|▍         | 226/5197 [00:17<05:35, 14.80it/s]
  4%|▍         | 228/5197 [00:17<05:48, 14.27it/s]
  4%|▍         | 231/5197 [00:17<05:03, 16.37it/s]
  4%|▍         | 233/5197 [00:17<04:49, 17.12it/s]
  5%|▍         | 235/5197 [00:17<04:39, 17.75it/s]
  5%|▍         | 237/5197 [00:17<05:31, 14.98it/s]
  5%|▍         | 240/5197 [00:18<04:47, 17.24it/s]
  5%|▍         | 242/5197 [00:18<04:55, 16.74it/s]
  5%|▍         | 245/5197 [00:18<04:32, 18.16it/s]
  5%|▍         | 249/5197 [00:18<04:37, 17.83it/s]
  5%|▍         | 251/5197 [00:18<05:00, 16.47it/s]
  5%|▍         | 253/5197 [00:19<06:59, 11.77it/s]
  5%|▍         | 256/5197 [00:19<06:36, 12.45it/s]
  5%|▍         | 259/5197 [00:19<07:12, 11.41it/s]
  5%|▌         | 261/5197 [00:19<07:12, 11.42it/s]
  5%|▌         | 263/5197 [00:19<07:33, 10.87it/s]
  5%|▌         | 265/5197 [00:20<07:01, 11.69it/s]
  5%|▌         | 267/5197 [00:20<06:19, 12.98it/s]
  5%|▌         | 270/5197 [00:20<05:22, 15.29it/s]
  5%|▌         | 274/5197 [00:20<04:05, 20.02it/s]
  5%|▌         | 277/5197 [00:20<05:07, 15.99it/s]
  5%|▌         | 279/5197 [00:20<05:07, 15.99it/s]
  5%|▌         | 284/5197 [00:20<03:38, 22.43it/s]
  6%|▌         | 287/5197 [00:21<03:36, 22.68it/s]
  6%|▌         | 290/5197 [00:21<03:34, 22.91it/s]
  6%|▌         | 293/5197 [00:21<04:09, 19.67it/s]
  6%|▌         | 296/5197 [00:21<04:32, 17.98it/s]
  6%|▌         | 299/5197 [00:21<04:26, 18.38it/s]
  6%|▌         | 302/5197 [00:21<04:40, 17.47it/s]
  6%|▌         | 304/5197 [00:22<04:41, 17.38it/s]
  6%|▌         | 307/5197 [00:22<04:26, 18.38it/s]
  6%|▌         | 310/5197 [00:22<04:19, 18.81it/s]
  6%|▌         | 312/5197 [00:22<04:16, 19.02it/s]
  6%|▌         | 314/5197 [00:22<06:23, 12.73it/s]
  6%|▌         | 316/5197 [00:23<06:42, 12.11it/s]
  6%|▌         | 318/5197 [00:23<06:06, 13.30it/s]
  6%|▌         | 321/5197 [00:23<05:57, 13.64it/s]
  6%|▌         | 323/5197 [00:23<05:40, 14.30it/s]
  6%|▋         | 327/5197 [00:23<04:14, 19.12it/s]
  6%|▋         | 330/5197 [00:23<03:56, 20.61it/s]
  6%|▋         | 333/5197 [00:23<03:49, 21.24it/s]
  6%|▋         | 337/5197 [00:23<03:14, 25.05it/s]
  7%|▋         | 340/5197 [00:24<03:12, 25.22it/s]
  7%|▋         | 343/5197 [00:24<05:30, 14.67it/s]
  7%|▋         | 346/5197 [00:24<04:51, 16.63it/s]
  7%|▋         | 349/5197 [00:24<05:09, 15.67it/s]
  7%|▋         | 351/5197 [00:24<05:04, 15.94it/s]
  7%|▋         | 354/5197 [00:25<04:49, 16.76it/s]
  7%|▋         | 356/5197 [00:25<04:43, 17.10it/s]
  7%|▋         | 358/5197 [00:25<05:08, 15.69it/s]
  7%|▋         | 360/5197 [00:25<05:05, 15.81it/s]
  7%|▋         | 362/5197 [00:25<05:02, 15.98it/s]
  7%|▋         | 365/5197 [00:25<04:37, 17.41it/s]
  7%|▋         | 367/5197 [00:25<06:04, 13.24it/s]
  7%|▋         | 369/5197 [00:26<06:44, 11.94it/s]
  7%|▋         | 372/5197 [00:26<05:44, 14.00it/s]
  7%|▋         | 374/5197 [00:26<05:20, 15.06it/s]
  7%|▋         | 376/5197 [00:26<05:14, 15.32it/s]
  7%|▋         | 378/5197 [00:26<05:03, 15.86it/s]
  7%|▋         | 380/5197 [00:26<06:35, 12.17it/s]
  7%|▋         | 382/5197 [00:27<07:22, 10.88it/s]
  7%|▋         | 384/5197 [00:27<06:54, 11.61it/s]
  7%|▋         | 386/5197 [00:27<07:22, 10.88it/s]
  7%|▋         | 388/5197 [00:27<07:09, 11.21it/s]
  8%|▊         | 391/5197 [00:27<05:50, 13.73it/s]
  8%|▊         | 393/5197 [00:28<05:57, 13.44it/s]
  8%|▊         | 397/5197 [00:28<04:13, 18.90it/s]
  8%|▊         | 400/5197 [00:28<04:50, 16.49it/s]
  8%|▊         | 402/5197 [00:28<04:47, 16.66it/s]
  8%|▊         | 405/5197 [00:28<04:44, 16.82it/s]
  8%|▊         | 407/5197 [00:28<06:16, 12.73it/s]
  8%|▊         | 409/5197 [00:29<05:51, 13.61it/s]
  8%|▊         | 414/5197 [00:29<04:22, 18.21it/s]
  8%|▊         | 416/5197 [00:29<05:28, 14.54it/s]
  8%|▊         | 419/5197 [00:29<05:03, 15.74it/s]
  8%|▊         | 421/5197 [00:29<04:55, 16.16it/s]
  8%|▊         | 424/5197 [00:29<05:23, 14.73it/s]
  8%|▊         | 427/5197 [00:30<04:35, 17.34it/s]
  8%|▊         | 429/5197 [00:30<04:30, 17.65it/s]
  8%|▊         | 431/5197 [00:30<05:23, 14.75it/s]
  8%|▊         | 434/5197 [00:30<04:42, 16.84it/s]
  8%|▊         | 436/5197 [00:30<05:03, 15.67it/s]
  8%|▊         | 438/5197 [00:30<06:37, 11.99it/s]
  8%|▊         | 440/5197 [00:31<06:13, 12.75it/s]
  9%|▊         | 442/5197 [00:31<05:41, 13.93it/s]
  9%|▊         | 444/5197 [00:31<05:55, 13.38it/s]
  9%|▊         | 446/5197 [00:31<05:24, 14.64it/s]
  9%|▊         | 448/5197 [00:31<05:23, 14.70it/s]
  9%|▊         | 450/5197 [00:31<05:20, 14.80it/s]
  9%|▊         | 453/5197 [00:31<05:15, 15.05it/s]
  9%|▉         | 455/5197 [00:32<05:38, 14.01it/s]
  9%|▉         | 457/5197 [00:32<05:24, 14.59it/s]
  9%|▉         | 459/5197 [00:32<05:36, 14.07it/s]
  9%|▉         | 461/5197 [00:32<05:36, 14.06it/s]
  9%|▉         | 464/5197 [00:32<04:40, 16.88it/s]
  9%|▉         | 466/5197 [00:32<05:13, 15.07it/s]
  9%|▉         | 468/5197 [00:32<04:53, 16.12it/s]
  9%|▉         | 471/5197 [00:33<07:31, 10.46it/s]
  9%|▉         | 473/5197 [00:33<06:46, 11.63it/s]
  9%|▉         | 475/5197 [00:33<06:00, 13.10it/s]
  9%|▉         | 477/5197 [00:33<06:25, 12.24it/s]
  9%|▉         | 479/5197 [00:33<07:06, 11.05it/s]
  9%|▉         | 481/5197 [00:34<06:23, 12.31it/s]
  9%|▉         | 483/5197 [00:34<06:20, 12.38it/s]
  9%|▉         | 486/5197 [00:34<05:29, 14.31it/s]
  9%|▉         | 489/5197 [00:34<04:46, 16.46it/s]
  9%|▉         | 492/5197 [00:34<04:21, 17.98it/s]
 10%|▉         | 495/5197 [00:34<04:41, 16.71it/s]
 10%|▉         | 498/5197 [00:35<04:15, 18.38it/s]
 10%|▉         | 501/5197 [00:35<03:48, 20.51it/s]
 10%|▉         | 504/5197 [00:35<03:59, 19.63it/s]
 10%|▉         | 507/5197 [00:35<03:57, 19.71it/s]
 10%|▉         | 510/5197 [00:35<04:42, 16.61it/s]
 10%|▉         | 512/5197 [00:35<04:35, 17.02it/s]
 10%|▉         | 514/5197 [00:35<04:36, 16.96it/s]
 10%|▉         | 516/5197 [00:36<04:41, 16.62it/s]
 10%|█         | 520/5197 [00:36<03:44, 20.80it/s]
 10%|█         | 523/5197 [00:36<03:29, 22.29it/s]
 10%|█         | 526/5197 [00:36<03:43, 20.93it/s]
 10%|█         | 529/5197 [00:36<04:56, 15.74it/s]
 10%|█         | 531/5197 [00:36<05:30, 14.11it/s]
 10%|█         | 533/5197 [00:37<05:08, 15.14it/s]
 10%|█         | 536/5197 [00:37<04:27, 17.45it/s]
 10%|█         | 538/5197 [00:37<04:22, 17.75it/s]
 10%|█         | 540/5197 [00:37<04:35, 16.88it/s]
 10%|█         | 542/5197 [00:37<04:49, 16.08it/s]
 10%|█         | 545/5197 [00:37<04:39, 16.67it/s]
 11%|█         | 549/5197 [00:37<04:16, 18.10it/s]
 11%|█         | 551/5197 [00:38<04:53, 15.82it/s]
 11%|█         | 554/5197 [00:38<04:25, 17.46it/s]
 11%|█         | 556/5197 [00:38<04:32, 17.01it/s]
 11%|█         | 559/5197 [00:38<04:01, 19.23it/s]
 11%|█         | 562/5197 [00:38<03:33, 21.73it/s]
 11%|█         | 565/5197 [00:38<03:16, 23.55it/s]
 11%|█         | 569/5197 [00:38<02:48, 27.42it/s]
 11%|█         | 572/5197 [00:38<03:10, 24.31it/s]
 11%|█         | 575/5197 [00:39<03:18, 23.32it/s]
 11%|█         | 579/5197 [00:39<02:51, 26.97it/s]
 11%|█         | 583/5197 [00:39<02:34, 29.78it/s]
 11%|█▏        | 587/5197 [00:39<02:57, 25.98it/s]
 11%|█▏        | 591/5197 [00:39<02:55, 26.24it/s]
 11%|█▏        | 597/5197 [00:39<02:24, 31.84it/s]
 12%|█▏        | 601/5197 [00:39<02:51, 26.87it/s]
 12%|█▏        | 604/5197 [00:40<02:57, 25.93it/s]
 12%|█▏        | 608/5197 [00:40<02:45, 27.69it/s]
 12%|█▏        | 612/5197 [00:40<02:58, 25.68it/s]
 12%|█▏        | 617/5197 [00:40<02:34, 29.74it/s]
 12%|█▏        | 621/5197 [00:40<03:26, 22.20it/s]
 12%|█▏        | 624/5197 [00:41<03:55, 19.46it/s]
 12%|█▏        | 628/5197 [00:41<03:17, 23.11it/s]
 12%|█▏        | 632/5197 [00:41<02:55, 25.95it/s]
 12%|█▏        | 636/5197 [00:41<03:18, 22.97it/s]
 12%|█▏        | 639/5197 [00:41<03:19, 22.86it/s]
 12%|█▏        | 643/5197 [00:41<02:56, 25.77it/s]
 12%|█▏        | 648/5197 [00:41<02:40, 28.35it/s]
 13%|█▎        | 652/5197 [00:42<03:05, 24.53it/s]
 13%|█▎        | 655/5197 [00:42<03:06, 24.34it/s]
 13%|█▎        | 658/5197 [00:42<03:06, 24.30it/s]
 13%|█▎        | 662/5197 [00:42<03:09, 23.99it/s]
 13%|█▎        | 665/5197 [00:42<03:16, 23.05it/s]
 13%|█▎        | 668/5197 [00:42<03:27, 21.88it/s]
 13%|█▎        | 671/5197 [00:42<03:46, 20.02it/s]
 13%|█▎        | 674/5197 [00:43<03:37, 20.77it/s]
 13%|█▎        | 678/5197 [00:43<03:08, 24.01it/s]
 13%|█▎        | 682/5197 [00:43<02:54, 25.83it/s]
 13%|█▎        | 685/5197 [00:43<03:39, 20.57it/s]
 13%|█▎        | 688/5197 [00:43<03:49, 19.67it/s]
 13%|█▎        | 691/5197 [00:43<03:30, 21.44it/s]
 13%|█▎        | 695/5197 [00:43<03:02, 24.68it/s]
 13%|█▎        | 698/5197 [00:44<03:00, 24.94it/s]
 14%|█▎        | 703/5197 [00:44<02:58, 25.23it/s]
 14%|█▎        | 706/5197 [00:44<03:51, 19.41it/s]
 14%|█▎        | 709/5197 [00:44<03:36, 20.71it/s]
 14%|█▎        | 712/5197 [00:44<03:18, 22.61it/s]
 14%|█▍        | 717/5197 [00:44<02:39, 28.10it/s]
 14%|█▍        | 721/5197 [00:45<02:43, 27.41it/s]
 14%|█▍        | 724/5197 [00:45<02:53, 25.78it/s]
 14%|█▍        | 727/5197 [00:45<03:31, 21.17it/s]
 14%|█▍        | 730/5197 [00:45<04:58, 14.97it/s]
 14%|█▍        | 733/5197 [00:45<04:43, 15.74it/s]
 14%|█▍        | 735/5197 [00:46<04:54, 15.14it/s]
 14%|█▍        | 738/5197 [00:46<04:41, 15.87it/s]
 14%|█▍        | 740/5197 [00:46<04:52, 15.21it/s]
 14%|█▍        | 742/5197 [00:46<05:18, 14.00it/s]
 14%|█▍        | 746/5197 [00:46<03:54, 18.98it/s]
 14%|█▍        | 749/5197 [00:46<03:40, 20.16it/s]
 14%|█▍        | 752/5197 [00:47<04:18, 17.20it/s]
 15%|█▍        | 755/5197 [00:47<03:45, 19.74it/s]
 15%|█▍        | 759/5197 [00:47<03:14, 22.86it/s]
 15%|█▍        | 763/5197 [00:47<02:56, 25.08it/s]
 15%|█▍        | 767/5197 [00:47<02:46, 26.65it/s]
 15%|█▍        | 770/5197 [00:47<03:14, 22.71it/s]
 15%|█▍        | 774/5197 [00:47<02:57, 24.94it/s]
 15%|█▍        | 777/5197 [00:47<02:51, 25.78it/s]
 15%|█▌        | 780/5197 [00:48<03:00, 24.41it/s]
 15%|█▌        | 783/5197 [00:48<03:11, 23.01it/s]
 15%|█▌        | 787/5197 [00:48<02:49, 26.04it/s]
 15%|█▌        | 792/5197 [00:48<02:22, 30.92it/s]
 15%|█▌        | 796/5197 [00:48<02:20, 31.25it/s]
 15%|█▌        | 800/5197 [00:48<02:12, 33.25it/s]
 15%|█▌        | 804/5197 [00:48<02:07, 34.57it/s]
 16%|█▌        | 808/5197 [00:48<02:26, 29.95it/s]
 16%|█▌        | 812/5197 [00:49<02:38, 27.61it/s]
 16%|█▌        | 817/5197 [00:49<02:15, 32.36it/s]
 16%|█▌        | 821/5197 [00:49<02:12, 32.95it/s]
 16%|█▌        | 825/5197 [00:49<02:06, 34.61it/s]
 16%|█▌        | 830/5197 [00:49<02:18, 31.64it/s]
 16%|█▌        | 834/5197 [00:49<02:21, 30.87it/s]
 16%|█▌        | 838/5197 [00:49<02:15, 32.21it/s]
 16%|█▌        | 842/5197 [00:50<02:17, 31.72it/s]
 16%|█▋        | 846/5197 [00:50<02:24, 30.12it/s]
 16%|█▋        | 850/5197 [00:50<02:38, 27.36it/s]
 16%|█▋        | 854/5197 [00:50<02:47, 25.96it/s]
 17%|█▋        | 858/5197 [00:50<02:32, 28.36it/s]
 17%|█▋        | 862/5197 [00:50<02:25, 29.77it/s]
 17%|█▋        | 866/5197 [00:50<02:15, 32.07it/s]
 17%|█▋        | 870/5197 [00:50<02:10, 33.14it/s]
 17%|█▋        | 874/5197 [00:51<02:33, 28.23it/s]
 17%|█▋        | 880/5197 [00:51<02:08, 33.61it/s]
 17%|█▋        | 885/5197 [00:51<01:57, 36.79it/s]
 17%|█▋        | 890/5197 [00:51<02:04, 34.53it/s]
 17%|█▋        | 895/5197 [00:51<02:03, 34.97it/s]
 17%|█▋        | 899/5197 [00:51<02:32, 28.19it/s]
 17%|█▋        | 903/5197 [00:52<02:48, 25.42it/s]
 17%|█▋        | 906/5197 [00:52<02:56, 24.27it/s]
 17%|█▋        | 909/5197 [00:52<02:55, 24.40it/s]
 18%|█▊        | 912/5197 [00:52<02:49, 25.32it/s]
 18%|█▊        | 916/5197 [00:52<02:38, 26.96it/s]
 18%|█▊        | 921/5197 [00:52<02:20, 30.49it/s]
 18%|█▊        | 925/5197 [00:52<02:45, 25.85it/s]
 18%|█▊        | 930/5197 [00:53<02:29, 28.49it/s]
 18%|█▊        | 939/5197 [00:53<01:47, 39.73it/s]
 18%|█▊        | 944/5197 [00:53<02:03, 34.55it/s]
 18%|█▊        | 948/5197 [00:53<02:55, 24.25it/s]
 18%|█▊        | 951/5197 [00:53<03:28, 20.32it/s]
 18%|█▊        | 954/5197 [00:54<03:46, 18.74it/s]
 18%|█▊        | 957/5197 [00:54<03:57, 17.86it/s]
 18%|█▊        | 960/5197 [00:54<03:46, 18.69it/s]
 19%|█▊        | 963/5197 [00:54<04:11, 16.87it/s]
 19%|█▊        | 965/5197 [00:54<05:19, 13.25it/s]
 19%|█▊        | 968/5197 [00:55<04:29, 15.71it/s]
 19%|█▊        | 971/5197 [00:55<04:13, 16.69it/s]
 19%|█▊        | 973/5197 [00:55<04:12, 16.73it/s]
 19%|█▉        | 975/5197 [00:55<04:30, 15.60it/s]
 19%|█▉        | 978/5197 [00:55<03:52, 18.18it/s]
 19%|█▉        | 980/5197 [00:55<04:09, 16.89it/s]
 19%|█▉        | 982/5197 [00:55<04:15, 16.53it/s]
 19%|█▉        | 984/5197 [00:56<05:15, 13.35it/s]
 19%|█▉        | 988/5197 [00:56<03:57, 17.71it/s]
 19%|█▉        | 990/5197 [00:56<04:35, 15.28it/s]
 19%|█▉        | 992/5197 [00:56<05:21, 13.08it/s]
 19%|█▉        | 995/5197 [00:56<04:22, 16.00it/s]
 19%|█▉        | 998/5197 [00:56<04:09, 16.82it/s]
 19%|█▉        | 1000/5197 [00:57<05:27, 12.82it/s]
 19%|█▉        | 1002/5197 [00:57<04:58, 14.04it/s]
 19%|█▉        | 1004/5197 [00:57<04:56, 14.15it/s]
 19%|█▉        | 1007/5197 [00:57<04:04, 17.15it/s]
 19%|█▉        | 1009/5197 [00:57<04:38, 15.05it/s]
 19%|█▉        | 1012/5197 [00:57<04:26, 15.73it/s]
 20%|█▉        | 1014/5197 [00:58<04:29, 15.51it/s]
 20%|█▉        | 1017/5197 [00:58<03:45, 18.52it/s]
 20%|█▉        | 1020/5197 [00:58<05:25, 12.83it/s]
 20%|█▉        | 1022/5197 [00:58<07:03,  9.86it/s]
 20%|█▉        | 1024/5197 [00:59<06:17, 11.04it/s]
 20%|█▉        | 1027/5197 [00:59<05:38, 12.31it/s]
 20%|█▉        | 1030/5197 [00:59<04:42, 14.78it/s]
 20%|█▉        | 1032/5197 [00:59<05:20, 13.00it/s]
 20%|█▉        | 1034/5197 [00:59<05:40, 12.24it/s]
 20%|█▉        | 1036/5197 [00:59<06:10, 11.24it/s]
 20%|█▉        | 1038/5197 [01:00<06:13, 11.14it/s]
 20%|██        | 1041/5197 [01:00<05:57, 11.62it/s]
 20%|██        | 1043/5197 [01:00<06:30, 10.64it/s]
 20%|██        | 1045/5197 [01:00<06:02, 11.46it/s]
 20%|██        | 1047/5197 [01:00<05:40, 12.21it/s]
 20%|██        | 1051/5197 [01:01<04:14, 16.29it/s]
 20%|██        | 1053/5197 [01:01<05:51, 11.77it/s]
 20%|██        | 1056/5197 [01:01<05:31, 12.48it/s]
 20%|██        | 1058/5197 [01:01<07:32,  9.15it/s]
 20%|██        | 1060/5197 [01:02<06:35, 10.47it/s]
 20%|██        | 1062/5197 [01:02<05:51, 11.77it/s]
 20%|██        | 1065/5197 [01:02<04:49, 14.30it/s]
 21%|██        | 1068/5197 [01:02<04:16, 16.13it/s]
 21%|██        | 1070/5197 [01:02<04:11, 16.40it/s]
 21%|██        | 1072/5197 [01:02<04:19, 15.91it/s]
 21%|██        | 1076/5197 [01:02<03:16, 20.92it/s]
 21%|██        | 1079/5197 [01:02<03:03, 22.42it/s]
 21%|██        | 1083/5197 [01:03<03:18, 20.77it/s]
 21%|██        | 1086/5197 [01:03<04:38, 14.78it/s]
 21%|██        | 1089/5197 [01:03<04:05, 16.71it/s]
 21%|██        | 1092/5197 [01:03<03:45, 18.18it/s]
 21%|██        | 1095/5197 [01:03<03:25, 19.97it/s]
 21%|██        | 1098/5197 [01:04<04:46, 14.33it/s]

In [69]:
# pass results into a pandas dataframe

emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [70]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273591,0.928168,0.932798,0.646216,0.967157,0.729603,9780002005883
1,0.612618,0.348285,0.942528,0.704422,0.887940,0.111690,0.252545,9780002261982
2,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078765,9780006178736
3,0.351483,0.150723,0.360707,0.251881,0.732687,0.111690,0.078765,9780006280897
4,0.081412,0.184495,0.095043,0.040564,0.884389,0.475881,0.078765,9780006280934
...,...,...,...,...,...,...,...,...
5192,0.148208,0.030643,0.919165,0.255170,0.853722,0.980877,0.030656,9788172235222
5193,0.064134,0.114383,0.051363,0.400263,0.883199,0.111690,0.227765,9788173031014
5194,0.009997,0.009929,0.339217,0.947779,0.375756,0.066685,0.057625,9788179921623
5195,0.064134,0.104007,0.459269,0.759455,0.951104,0.368110,0.078765,9788185300535
5196,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765,9789027712059

In [71]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [72]:
# merge into books df
books = pd.merge(books, emotions_df, on="isbn13")

In [73]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273591,0.928168,0.932798,0.646216,0.967157,0.729603
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612618,0.348285,0.942528,0.704422,0.887940,0.111690,0.252545
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078765
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction,0.351483,0.150723,0.360707,0.251881,0.732687,0.111690,0.078765
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction,0.081412,0.184495,0.095043,0.040564,0.884389,0.475881,0.078765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction,0.148208,0.030643,0.919165,0.255170,0.853722,0.980877,0.030656
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction,0.064134,0.114383,0.051363,0.400263,0.883199,0.111690,0.227765
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction,0.009997,0.009929,0.339217,0.947779,0.375756,0.066685,0.057625
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction,0.064134,0.104007,0.459269,0.759455,0.951104,0.368110,0.078765
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765

In [74]:
## YAY DONE! save into csv now
books.to_csv("books_with_emotion.csv", index=False)