In [2]:
from langchain_community.document_loaders import TextLoader # takes raw text and converts into text that langchain can read
from langchain_text_splitters import CharacterTextSplitter # splits desc document into meaningful chunks
from langchain_openai import OpenAIEmbeddings # converting chunks into document embeddings for api calls
from langchain_chroma import Chroma # store in vector database

In [16]:
from dotenv import load_dotenv
load_dotenv()

True

In [17]:
# read in dataset
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [18]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [19]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: str

In [10]:
# put tagged description into its own csv text file
books["tagged_description"].to_csv("tagged_description.txt",
                                   index = False,
                                   header = False)

In [39]:
# start splitting data by loading and instantiating text split up
raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=0.1, chunk_overlap=0, separator="\n") # chunk size = 0 to prioritize splitting on seperator and not chunk size, no overlap for chunks

# done w instantiation of text splitter, now apply to documents
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1170, which is longer than the specified 0
Created a chunk of size 1216, which is longer than the specified 0
Created a chunk of size 375, which is longer than the specified 0
Created a chunk of size 311, which is longer than the specified 0
Created a chunk of size 483, which is longer than the specified 0
Created a chunk of size 484, which is longer than the specified 0
Created a chunk of size 962, which is longer than the specified 0
Created a chunk of size 188, which is longer than the specified 0
Created a chunk of size 845, which is longer than the specified 0
Created a chunk of size 296, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 881, which is longer than the specified 0
Created a chunk of size 1090, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 213, which is longer than the specified 0
Created a chunk of size 216, which is longer than the specified 0
Created a chunk of size 515, which is longer than the specified 0
Created a chunk of size 754, which is longer than the specified 0
Created a chunk of size 390, which is longer than the specified 0
Created a chunk of size 265, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 730, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 258, which is longer than the specified 0
Created a chunk of size 475, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 1267, which is longer than the specified 0
Created a chunk of size 683, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 555, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 282, which is longer than the specified 0
Created a chunk of size 789, which is longer than the specified 0
Created a chunk of size 566, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 179, which is longer than the specified 0
Created a chunk of size 299, which is longer than the specified 0
Created a chunk of size 535, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 565, which is longer than the specified 0
Created a chunk of size 385, which is longer than the specified 0
Created a chunk of size 412, which is longer than the specified 0
Created a chunk of size 463, which is longer than the specified 0
Created a chunk of size 597, which is longer than the specified 0
Created a chunk of size 478, which is longer than the specified 0
Created a chunk of size 461, which is longer than the specified 0
Created a chunk of size 259, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 616, which is longer than the specified 0
Created a chunk of size 421, which is longer than the specified 0
Created a chunk of size 889, which is longer than the specified 0
Created a chunk of size 695, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 219, which is longer than the specified 0
Created a chunk of size 277, which is longer than the specified 0
Created a chunk of size 2010, which is longer than the specified 0
Created a chunk of size 175, which is longer than the specified 0
Created a chunk of size 481, which is longer than the specified 0
Created a chunk of size 302, which is longer than the specified 0
Created a chunk of size 522, which is longer than the specified 0
Created a chunk of size 649, which is longer than the specified 0
Created a chunk of size 778, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 550, which is longer than the specified 0
Created a chunk of size 1225, which is longer than the specified 0
Created a chunk of size 408, which is longer than the specified 0
Created a chunk of size 1186, which is longer than the specified 0
Created a chunk of size 1216, which is longer than the specified 0
Created a chunk of size 1193, which is longer than the specified 0
Created a chunk of size 1059, which is longer than the specified 0
Created a chunk of size 246, which is longer than the specified 0
Created a chunk of size 690, which is longer than the specified 0
Created a chunk of size 878, which is longer than the specified 0
Created a chunk of size 286, which is longer than the specified 0
Created a chunk of size 768, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 419, which is longer than the specified 0
Created a chunk of size 210, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 725, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 528, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 340, which is longer than the specified 0
Created a chunk of size 901, which is longer than the specified 0
Created a chunk of size 1272, which is longer than the specified 0
Created a chunk of size 560, which is longer than the specified 0
Created a chunk of size 1637, which is longer than the specified 0
Created a chunk of size 438, which is longer than the specified 0
Created a chunk of size 251, which is longer than the specified 0
Created a chunk of size 779, which is longer than the specified 0
Created a chunk of size 718, which is longer than the specified 0
Created a chunk of size 516, which is longer than the specified 0
Created a chunk of size 960, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 1132, which is longer than the specified 0
Created a chunk of size 170, which is longer than the specified 0
Created a chunk of size 1325, which is longer than the specified 0
Created a chunk of size 853, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 801, which is longer than the specified 0
Created a chunk of size 1121, which is longer than the specified 0
Created a chunk of size 838, which is longer than the specified 0
Created a chunk of size 262, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 734, which is longer than the specified 0
Created a chunk of size 1195, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 775, which is longer than the specified 0
Created a chunk of size 280, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 358, which is longer than the specified 0
Created a chunk of size 768, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 718, which is longer than the specified 0
Created a chunk of size 2012, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 1288, which is longer than the specified 0
Created a chunk of size 1231, which is longer than the specified 0
Created a chunk of size 729, which is longer than the specified 0
Created a chunk of size 750, which is longer than the specified 0
Created a chunk of size 447, which is longer than the specified 0
Created a chunk of size 1242, which is longer than the specified 0
Created a chunk of size 311, which is longer than the specified 0
Created a chunk of size 914, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 846, which is longer than the specified 0
Created a chunk of size 1128, which is longer than the specified 0
Created a chunk of size 1075, which is longer than the specified 0
Created a chunk of size 1320, which is longer than the specified 0
Created a chunk of size 363, which is longer than the specified 0
Created a chunk of size 2834, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 572, which is longer than the specified 0
Created a chunk of size 208, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 1006, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 2510, which is longer than the specified 0
Created a chunk of size 956, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 351, which is longer than the specified 0
Created a chunk of size 641, which is longer than the specified 0
Created a chunk of size 405, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 795, which is longer than the specified 0
Created a chunk of size 167, which is longer than the specified 0
Created a chunk of size 391, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 1424, which is longer than the specified 0
Created a chunk of size 1085, which is longer than the specified 0
Created a chunk of size 1146, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 790, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 808, which is longer than the specified 0
Created a chunk of size 1814, which is longer than the specified 0
Created a chunk of size 1830, which is longer than the specified 0
Created a chunk of size 1064, which is longer than the specified 0
Created a chunk of size 955, which is longer than the specified 0
Created a chunk of size 1182, which is longer than the specified 0
Created a chunk of size 283, which is longer than the specified 0
Created a chunk of size 283, which is longer than the specified 0
Created a chunk of size 288, which is longer than the specified 0
Created a chunk of size 1286, which is longer than the specified 0
Created a chunk of size 1644, which is longer than the specified 0
Created a chunk of size 759, which is longer than the specified 0
Created a chunk of size 1932, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 2008, which is longer than the specified 0
Created a chunk of size 2285, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 1003, which is longer than the specified 0
Created a chunk of size 579, which is longer than the specified 0
Created a chunk of size 290, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 1144, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 1483, which is longer than the specified 0
Created a chunk of size 223, which is longer than the specified 0
Created a chunk of size 1137, which is longer than the specified 0
Created a chunk of size 724, which is longer than the specified 0
Created a chunk of size 668, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 608, which is longer than the specified 0
Created a chunk of size 572, which is longer than the specified 0
Created a chunk of size 967, which is longer than the specified 0
Created a chunk of size 859, which is longer than the specified 0
Created a chunk of size 1034, which is longer than the specified 0
Created a chunk of size 191, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 497, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 350, which is longer than the specified 0
Created a chunk of size 735, which is longer than the specified 0
Created a chunk of size 527, which is longer than the specified 0
Created a chunk of size 1017, which is longer than the specified 0
Created a chunk of size 972, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 690, which is longer than the specified 0
Created a chunk of size 546, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 378, which is longer than the specified 0
Created a chunk of size 933, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 856, which is longer than the specified 0
Created a chunk of size 717, which is longer than the specified 0
Created a chunk of size 749, which is longer than the specified 0
Created a chunk of size 714, which is longer than the specified 0
Created a chunk of size 326, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 1090, which is longer than the specified 0
Created a chunk of size 725, which is longer than the specified 0
Created a chunk of size 247, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 706, which is longer than the specified 0
Created a chunk of size 1914, which is longer than the specified 0
Created a chunk of size 397, which is longer than the specified 0
Created a chunk of size 487, which is longer than the specified 0
Created a chunk of size 622, which is longer than the specified 0
Created a chunk of size 561, which is longer than the specified 0
Created a chunk of size 558, which is longer than the specified 0
Created a chunk of size 388, which is longer than the specified 0
Created a chunk of size 231, which is longer than the specified 0
Created a chunk of size 427, which is longer than the specified 0
Created a chunk of size 418, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 168, which is longer than the specified 0
Created a chunk of size 626, which is longer than the specified 0
Created a chunk of size 2616, which is longer than the specified 0
Created a chunk of size 1580, which is longer than the specified 0
Created a chunk of size 391, which is longer than the specified 0
Created a chunk of size 996, which is longer than the specified 0
Created a chunk of size 849, which is longer than the specified 0
Created a chunk of size 265, which is longer than the specified 0
Created a chunk of size 338, which is longer than the specified 0
Created a chunk of size 1530, which is longer than the specified 0
Created a chunk of size 215, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 2032, which is longer than the specified 0
Created a chunk of size 398, which is longer than the specified 0
Created a chunk of size 1619, which is longer than the specified 0
Created a chunk of size 700, which is longer than the specified 0
Created a chunk of size 824, which is longer than the specified 0
Created a chunk of size 356, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 510, which is longer than the specified 0
Created a chunk of size 665, which is longer than the specified 0
Created a chunk of size 1284, which is longer than the specified 0
Created a chunk of size 262, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 217, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 1277, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0
Created a chunk of size 380, which is longer than the specified 0
Created a chunk of size 271, which is longer than the specified 0
Created a chunk of size 179, which is longer than the specified 0
Created a chunk of size 227, which is longer than the specified 0
Created a chunk of size 224, which is longer than the specified 0
Created a chunk of size 784, which is longer than the specified 0
Created a chunk of size 971, which is longer than the specified 0
Created a chunk of size 615, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 759, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 247, which is longer than the specified 0
Created a chunk of size 965, which is longer than the specified 0
Created a chunk of size 234, which is longer than the specified 0
Created a chunk of size 845, which is longer than the specified 0
Created a chunk of size 788, which is longer than the specified 0
Created a chunk of size 650, which is longer than the specified 0
Created a chunk of size 986, which is longer than the specified 0
Created a chunk of size 799, which is longer than the specified 0
Created a chunk of size 193, which is longer than the specified 0
Created a chunk of size 1163, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 203, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0

In [40]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

In [41]:
##### CREATE VECTOR DATABASE
db_books= Chroma.from_documents(documents, embedding=OpenAIEmbeddings())

In [42]:
##### START OF QUERYING SECTION (YAY)

query = "A book to teach children about nature"
# get recommendations
docs = db_books.similarity_search(query, k = 10) # k is the number of results search returns
docs

[Document(id='6cb4d89a-11d6-471e-b12d-bd77874c4b8f', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(id='47659dc5-1a95-4c85-90f6-3f974bde001f', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(id='3e2e729f-c0cb-47e4-820c-7f6ac264e9a0', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='64ce69f6-5e54-4368-be3f-6d133f1d8036', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='2486e5d2-c711-415e-92a2-2207cefcb35d', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='6497708c-f59e-4223-84dd-6a28b2c20ce3', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='5534933b-d4bb-4a37-83be-598130ad331b', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(id='de4e244a-cd79-4dae-bec7-8420ede15e9e', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(id='3bd06b83-ada2-408a-ab8f-55084a30d4a0', metadata={'source': 'tagged_description.txt'}, page_content='"9780689861130 Children will love joining in and imitating the animal noises and sounds in this big, bold board book format, illustrated with Sandra Boynton\'s seriously silly signature animals."'),
 Document(id='12bed19e-0a04-43cd-a944-250e9a31dd95', metadata={'source': 'tagged_description.txt'}, page_content='"9780689861130 Children will love joining in and imitating the animal noises and sounds in this big, bold board book format, illustrated with Sandra Boynton\'s seriously silly signature animals."')]

In [43]:
# extract title from the description using the isbn number
isbn_str = docs[0].page_content.split()[0].strip().strip('"')
isbn_num = int(isbn_str)

books[books["isbn13"] == isbn_num]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [46]:
# bundle into a function so it gives us all the recommendations
def get_semantic_recommendations(query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    # get recommendations
    recs = db_books.similarity_search(query, k = 50)

    # create list to hold all the isbn of recommendations
    books_list = []
    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    # return books dataset that matches the isbn (all the recommended books)
    return books[books["isbn13"].isin(books_list)]

In [47]:
get_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
31,9780007105045,0007105045,Tree and Leaf,John Ronald Reuel Tolkien,Literary Collections,http://books.google.com/books/content?id=aPb_A...,"""The two works 'On fairy-stories' and 'Leaf by...",2001.0,4.09,176.0,2245.0,Tree and Leaf: The Homecoming of Beorhtnoth : ...,"9780007105045 ""The two works 'On fairy-stories..."
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,The Deer in the Wood,9780064434980 Even the youngest child can enjo...
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208 First published more than three ...
692,9780140448009,0140448004,Three Tales,Gustave Flaubert;Roger Whitehouse;Geoffrey Wall,Fiction,http://books.google.com/books/content?id=XFzga...,Features short fiction by the French naturalis...,2005.0,3.71,110.0,3050.0,Three Tales,9780140448009 Features short fiction by the Fr...
1078,9780241003008,0241003008,The Very Hungry Caterpillar,Eric Carle,Babytime resource,http://books.google.com/books/content?id=DpGEQ...,Eric Carle's children's classic is the story o...,1994.0,4.29,26.0,340101.0,The Very Hungry Caterpillar,9780241003008 Eric Carle's children's classic ...
1639,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,Everything on a Waffle,9780374422080 This Newbery Honor Book tells th...
2201,9780440362050,0440362059,My Name is Aram,William Saroyan,Fiction,http://books.google.com/books/content?id=2P3XA...,A small boy finds excitement and promise in th...,1966.0,4.15,151.0,975.0,My Name is Aram,9780440362050 A small boy finds excitement and...
2806,9780571090242,0571090249,Death of a Naturalist,Seamus Heaney,Poetry,http://books.google.com/books/content?id=et6dA...,Death of a Naturalist marks the auspicious out...,1969.0,4.29,57.0,63.0,Death of a Naturalist: Volume one,9780571090242 Death of a Naturalist marks the ...
3201,9780689823824,0689823827,A Child's Garden of Verses,Robert Louis Stevenson,Juvenile Fiction,http://books.google.com/books/content?id=luTZA...,"Here is a delightful look at childhood, writte...",1999.0,4.30,67.0,21780.0,A Child's Garden of Verses,9780689823824 Here is a delightful look at chi...
3214,9780689861130,0689861133,"Moo, Baa, la la La!",Sandra Boynton,Animal sounds,http://books.google.com/books/content?id=Gz40A...,Children will love joining in and imitating th...,2004.0,4.20,14.0,28261.0,"Moo, Baa, la la La!",9780689861130 Children will love joining in an...
3442,9780744578263,0744578264,The Sea-thing Child,Russell Hoban,Birds,http://books.google.com/books/content?id=CEt9O...,"Washed up on the beach during a storm, the sea...",2000.0,3.79,48.0,100.0,The Sea-thing Child,9780744578263 Washed up on the beach during a ...
3581,9780763620875,0763620874,Judy Moody Saves the World!,Megan McDonald,Juvenile Fiction,http://books.google.com/books/content?id=xDIRB...,When Judy Moody gets serious about protecting ...,2004.0,4.03,160.0,5883.0,Judy Moody Saves the World!,9780763620875 When Judy Moody gets serious abo...
3582,9780763621643,0763621641,Castle Diary,Richard Platt;Chris Riddell,Juvenile Fiction,http://books.google.com/books/content?id=rFUBA...,As a page in his uncle's castle in thirteenth-...,2003.0,3.84,128.0,1072.0,Castle Diary: The Journal of Tobias Burgess,9780763621643 As a page in his uncle's castle ...
3591,9780764122781,0764122789,Aquatic Turtles,Richard D. Bartlett;Patricia Bartlett,Pets,http://books.google.com/books/content?id=ket2b...,Titles in this series present basic informatio...,2003.0,3.80,46.0,20.0,"Aquatic Turtles: Sliders, Cooters, Painted, an...",9780764122781 Titles in this series present ba...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, ..."
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,Baby Einstein: Babies,"9780786808380 Introduce your babies to birds, ..."
3750,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,Baby Einstein: Dogs,"9780786808397 Introduce your baby to birds, ca..."
3751,9780786808717,0786808713,Baby Einstein: What Does Violet See? Raindrops...,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=95IIA...,A very special puddle sets Violet the mouse of...,2002.0,3.25,18.0,16.0,Baby Einstein: What Does Violet See? Raindrops...,9780786808717 A very special puddle sets Viole...
3760,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,375.0,The Big Box,9780786812912 In her first illustrated book fo...
3765,9780786819119,0786819111,"Baby Einstein: Water, Water Everywhere","Disney Book Group,",Juvenile Fiction,http://books.google.com/books/content?id=tuAdA...,Charming illustrations and playful rhythmic ve...,2003.0,3.70,10.0,77.0,"Baby Einstein: Water, Water Everywhere",9780786819119 Charming illustrations and playf...
3797,9780789458209,0789458209,Tree,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=Qwsqj...,Photographs and text explore the anatomy and l...,2000.0,4.07,64.0,5.0,Tree,9780789458209 Photographs and text explore the...
4264,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,8.0,The Little Big Book for God's Children,9780941807555 THE LITTLE BIG BOOK FOR GOD'S CH...
4331,9781400033850,1400033853,Providence of a Sparrow,Chris Chester,Biography & Autobiography,http://books.google.com/books/content?id=Z7RDD...,Describes the influence of a foundling baby sp...,2004.0,4.32,304.0,218.0,Providence of a Sparrow: Lessons from a Life G...,9781400033850 Describes the influence of a fou...
4557,9781551052700,1551052709,Ecuador Nature Guide,Christopher D. Jiggins,Botanique,http://books.google.com/books/content?id=1JjbG...,The guide provides information on 76 species o...,2000.0,5.00,96.0,1.0,Ecuador Nature Guide: Southwest Forests : Sozo...,9781551052700 The guide provides information o...